### ISSUE TITLE
Buggy restore selection when creating link on first word in paragraph

### ISSUE THREAD

**Issue by Olgagr** [yabwe/medium-editor#757]
Steps to reproduce: 

1. Create a new paragraph
2. Select first word in paragraph
3. Create a link
4. this.base.restoreSelection() doesn't restore selection on link correctly (what is visually seen). MediumEditor.selection.getSelectionStart(this.base.options.ownerDocument) returns previous paragraph, not anchor node from current paragraph. It is problematic when you want to apply custom class on link or, in my case, add custom data attributes to link.

![mediumeditor___demo](https://cloud.githubusercontent.com/assets/1297219/9031800/37a8c590-39b8-11e5-831e-4c7b3856d87b.png)

**Comment by nmielnik** [comment]
We're working on a fix for this, there should be a PR coming shortly

**Comment by Olgagr** [comment]
Hmm, for me this bugfix doesn't work. It causes that the url of the link is prepended into content before the selcted word. 
I'm on version 4.12.6. However, this code you corrected seems to be the same in this version.

**Comment by nmielnik** [comment]
@Olgagr I've updated the running version 4.12.x branch with as many of our fixes as I could easily port over.  As far as I can tell, it seems like the issue is now fixed in version 4.12.7, which has just been published to npm.  Please let us know if the issue is fixed for you there.

As version 5+ continues to diverge from our old 4 branch, less and less bug fixes will be able to be ported back, so I would definitely recommend an upgrade at some point in the near future if possible.

We have [Documentation for upgrading to v5](https://github.com/yabwe/medium-editor/blob/master/UPGRADE-5.md) which hopefully can make it less painful.

**Comment by Olgagr** [comment]
@nmielnik Thanks Guys for help and involvement. Of course I'll update to version 5, but right now I have too many extensions and even a plugin written for version 4, so this is not possible to make a migration.

I checked version 4.12.7 and the situation a little bit improved. So if I have a situation like this:

[empty paragraph]
link_on_first_word_in_paragraph other words in paragraph

this work perfectly well. However, when I have situation:

some paragraph
link_on_first_word_in_paragraph other words in paragraph

I still get selection not on word that should be a link (see attachment).

![twipe_publishing_tools](https://cloud.githubusercontent.com/assets/1297219/9084296/67bcd9d6-3b72-11e5-8d23-b6b25bd3e5bc.png)

**Comment by Olgagr** [comment]
@nmielnik To be sure that this is not my code issue, I also checked version 5.5.4 from master branch. The above bug still exists also in this version. I test it in Plunker: http://plnkr.co/edit/vMlgGl?p=preview

**Comment by nmielnik** [comment]
The fix for this should be in version 5.6.1 and 4.12.8

**Comment by Olgagr** [comment]
@nmielnik I can confirm it works for 4.12.8. Thank you!

**Comment by nmielnik** [comment]
Thanks a ton for opening the issue! Apparently these issues have been around for a while and we hadn't know about them.
