### ISSUE TITLE
event.preventDefault or disableDoubleReturn don't work when element is other than a 'p' tag

### ISSUE THREAD

**Issue by MindRave** [yabwe/medium-editor#924]
First and foremost, thank you for the excellent plugin!

I am getting issues when using 'disableDoubleReturn' or just a simple preventDefault on hitting Enter, when the node (line) is empty.

When the element is a simple 'p' tag, everything works as expected. No content = no new line created on "Return'. I need to write something inside the created line to be able to press Enter and create another one.

However, when I write something in the line, call up the toolbar and transform it into an 'h2' from a 'p', then delete everything in that 'h2' and press 'Return', the line returns as usually. Same for the 'h3'.

Is this an issue or wanted behaviour? If it's the latter, how would I go about overriding it? If it's the first, maybe someone can point me in the right direction to fix it?

Thank you in advance!

**Comment by rishijain** [comment]
which browser you are trying on and the version of medium-editor?

**Comment by MindRave** [comment]
@rishijain Chrome (47 - latest, apparently) and the latest version of Medium Editor installed through "npm install medium-editor"

**Comment by rishijain** [comment]
This is definitely a bug. Although I could only reproduce the issue on chrome. It worked fine on safari and firefox. Could you also confirm if this is the case with you too? 
If you want to try to fix the bug or find the reason why it happens, search for the definition of ```function handleDisabledEnterKeydown``` in `medium-editor.js`. This is the function which is responsible for handling the behaviour of `enter` key.

**Comment by MindRave** [comment]
@rishijain I was able to reproduce it in all major browsers: Chrome, Firefox and Safari (all latest versions, updated).

I've been looking into that function since yesterday. It's quite a long "if" statement, checking for the following:
"if current text selection is empty OR previous sibling text is empty OR it is not a list".

Playing around with it and logging out whether the condition is satisfied works well. What's weird is that even if the element is an empty 'h2', and I press 'Return', it is also satisfied. The line is empty and even the KeyboardEvent is logged as 'defaultPrevented: true'.

Puzzling, to say the least.

**Comment by rishijain** [comment]
@MindRave I am sorry. All this while I was testing against a different branch(not `MASTER`). Finally I tried it with latest master and I could not reproduce the issue you are getting. These are the steps I followed, let me know if this is what you did:

This is what my html looks like:

```ruby
<div class="editable">
  <p>It is a test</p>
</div>
```

and 

```javascript
var editor = new MediumEditor('.editable', {
  disableDoubleReturn: true
})
```

1. Select the `p` tag and remove the text and press `enter` key. Expected behaviour is nothing should happen, no new line being added. And this is what it did.

2. Add some text to `p` tag and select it. Change it to `h2` or `h3` tag and delete all the text now. The element is still `h2`. Now press `enter` key. Expected behaviour is same as it be with `p` tag. And it worked just like it should.

Tried this on different browsers. 

Can you double check if you have the latest version of medium-editor?

**Comment by MindRave** [comment]
@rishijain No worries, thank you for your help!

Unfortunately, I'm having the issue on medium-editor 5.12.0.

Used your setup from above.

1. Select 'p' tag and remove the text and press 'enter' key. Expected behaviour is nothing should happen, no new line being added. And this is what it did.
--- Indeed. Same for me.

2. Add some text to p tag and select it. Change it to h2 or h3 tag and delete all the text now. The element is still h2. Now press enter key. Expected behaviour is same as it be with p tag. And it worked just like it should.
--- Not same. h2, h3, Enter functions as a normal enter, adding new lines (h2 or h3) underneath.

(I'll try and make a video or GIF to show the issue)

**Comment by MindRave** [comment]
@rishijain Below you'll find a gif with a screencast of the issue, and a small Github repo of a "blank" setup.

Screen:
![meded](https://cloud.githubusercontent.com/assets/4063406/12223654/4093fa78-b7dd-11e5-8133-ab4199f1f37a.gif)

Github Repo:
https://github.com/MindRave/meded-temp

**Comment by rishijain** [comment]
@MindRave I have pushed a fix. This should fix the problem. Let me know if otherwise.

**Comment by derekoakley** [comment]
Just downloaded master to try it out and I still see an issue. If I type something and hit return and then choose h1 or h2 but don't type anything I can still return which creates empty p elements

**Comment by rishijain** [comment]
@derekoakley When you type something, place the cursor at the end of the node with text and press `enter`. it would create empty `p` tag(irrespective of whether it is a `p` or `h2` or `h3` tag). Keep repeating this process and it would keep creating new `p` tags. But when you press `enter` placing cursor at the end of new p tags(with no text in them), no new `p` tag is created.
